# Generated by Django 3.1.7 on 2021-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelform1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=20)),
                ('thk', models.IntegerField()),
                ('ka', models.IntegerField()),
                ('humusz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modelform2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p2o5', models.CharField(max_length=20)),
                ('k2o', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projectname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=20)),
            ],
        ),
    ]
