# Generated by Django 3.1.7 on 2021-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formexample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', models.CharField(max_length=100)),
            ],
        ),
    ]
