# Generated by Django 3.1.7 on 2021-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formexample', '0002_coordsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StainerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CoordsModel',
        ),
    ]
