# Generated by Django 3.1.7 on 2021-06-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formexample', '0003_auto_20210602_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stainermodel',
            old_name='colors',
            new_name='st_colors',
        ),
    ]
